server:
  port: 9002

spring:
  application:
    name: nacos-payment-consumner
  cloud:
    nacos:
      discovery:
        server-addr: localhost:7848

management:
  endpoints:
    web:
      exposure:
        include: '*'